name: Build and publish library

on: push

permissions:
  actions: read
  contents: write
  packages: write
  id-token: write

env:
  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'docs:') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - run: yarn --immutable
      - run: yarn test
      - run: yarn build

      - name: Summarize tsup build
        run: |
          ./scripts/meta.mjs libs/pino-logger >> $GITHUB_STEP_SUMMARY
          ./scripts/meta.mjs libs/next-logger >> $GITHUB_STEP_SUMMARY

      - name: Set next version
        run: |
          TEMP_VERSION=$(date +'%Y%m%d%H%M%S')
          jq --arg v "4.3.0-$TEMP_VERSION" '.version = $v' libs/pino-logger/package.json > libs/pino-logger/package.tmp.json && mv libs/pino-logger/package.tmp.json libs/pino-logger/package.json
          jq --arg v "4.3.0-$TEMP_VERSION" '.version = $v' libs/next-logger/package.json > libs/next-logger/package.tmp.json && mv libs/next-logger/package.tmp.json libs/next-logger/package.json

      - name: Publish pino-logger
        if: github.ref == 'refs/heads/main' || startsWith(github.ref_name, 'chore/esm-only')
        run: yarn npm publish --tag next
        working-directory: libs/pino-logger

      - name: Publish next-logger
        if: github.ref == 'refs/heads/main' || startsWith(github.ref_name, 'chore/esm-only')
        run: yarn npm publish --tag next
        working-directory: libs/next-logger

  increment-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Setup github connection for auth
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: yarn version -i patch
        working-directory: libs/next-logger
      - run: yarn version -i patch
        working-directory: libs/pino-logger
      - run: git add . && git commit -m "[skip ci] bump version to $(jq -r .version libs/pino-logger/package.json)" && git push
