name: Build and publish beta

on:
  push:
    branches:
      - grafana

permissions:
  actions: read
  contents: write
  packages: write
  id-token: write

env:
  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'docs:') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - run: yarn --immutable
      - run: yarn test
      - run: yarn build

      - name: Summarize tsup build
        run: |
          ./scripts/meta.mjs libs/pino-logger >> $GITHUB_STEP_SUMMARY
          ./scripts/meta.mjs libs/next-logger >> $GITHUB_STEP_SUMMARY

      - run: |
          TEMP_VERSION=$(date +'%Y%m%d%H%M%S')
          jq --arg v "4.4.0-$TEMP_VERSION" '.version = $v' libs/pino-logger/package.json > libs/pino-logger/package.tmp.json && mv libs/pino-logger/package.tmp.json libs/pino-logger/package.json
          jq --arg v "4.4.0-$TEMP_VERSION" '.version = $v' libs/next-logger/package.json > libs/next-logger/package.tmp.json && mv libs/next-logger/package.tmp.json libs/next-logger/package.json

      - name: Publish pino-logger
        run: yarn npm publish --tag=beta
        working-directory: libs/pino-logger

      - name: Publish next-logger
        run: yarn npm publish --tag=beta
        working-directory: libs/next-logger
